target = "latest"
no_ssl_verify = false
ignore_warning = false
show_full_path = false
upgrade = false
no_color = false
filter = []
ignores = ["python"]
no_recursive = false
ignore_additional_labels = false
default_venv = ".venv"
interactive = false
txt = false
init = false
path = "environment.yml"
extra = []
pre = false
fail_on_update = false
loggable = false
version = true
